// M4 seed generator — emits the full format seed as client-agnostic SQL.
//
// The M3 seed was hand-authored, which meant the format definition lived in two places
// and could silently disagree. This generator reads `m4-format.mjs` and `clock-order.mjs`
// directly, so the seed IS the format definition rather than a transcription of it. Any
// change to SHAPES, IMAGING, the grid or the depth targets reaches the database by
// re-running this, and `tools/clock-order.mjs` reports exactly what gets emitted.
//
//   node tools/m4-seed.mjs > packages/schema/seed/m4-clubfm-seed.sql
//   npm run seed -w @rotavox/schema -- seed/m4-clubfm-seed.sql
//
// Requires a library re-sync FIRST: song_categories derives from songs.rdj_subcategory_id
// and the mirror is a derived cache (ADR-0001). Seeding against a stale mirror maps
// categories to yesterday's pool assignment.
import {
  SHAPES, IMAGING, BLOCKS, CUR, REC, GOLD, TURNOVER, TOH_TURNOVER,
  HORIZONTAL, FORMAT_CYCLE_WEEKS, cellFor, identityOf,
} from "./m4-format.mjs";
import { clockSequence, fallbackFor } from "./clock-order.mjs";

const STATION = process.env.STATION_ID ?? "6a42a599-acfc-404f-a524-9fb9b65d36f3";
// Anchors week 0 of the rotation cycle. Local calendar date only; time is ignored.
// Must be stable forever — moving it flips which week every GH hour is on.
const EPOCH = process.env.FORMAT_EPOCH ?? "2026-08-03";

/**
 * LIBRARY ↔ CLOCKSET CONTRACT — the binding between scheduler categories and RadioDJ
 * subcategory IDs. Its absence let subcategory 34 sit unmapped through the whole M2 era,
 * so it is declared here explicitly and asserted at the end of the seed.
 *
 * B is subcat 1 alone: B1/B2 were consolidated 2026-08-02 because the clock model has a
 * single B (CUR below). Subcat 5 is retired, not deleted.
 */
const SUBCAT = {
  A1: [4], A2: [2], B: [1], C: [3], N: [23],
  R1: [24], R2: [25], R3: [26],
  G2010: [29], G2000: [28], G1990: [27], H1: [30], H2: [49],
  Discovery: [6], F: [31], GDEEP: [37],
  "TOH ES": [40], "TOH FF": [41], "TOH HD": [42], "TOH CO": [43], "TOH WW": [44],
  "TOH WD": [45], "TOH GH": [46], "TOH EM": [47], "TOH DN": [48],
  Liners: [9], "New-Music Sweepers": [33], "Gold Backsells": [34],
  "Relaunch Sweepers": [8], "Station Promos": [12], "Heritage Backsells": [35],
};

const PARENT = {
  ...Object.fromEntries(CUR.map((c) => [c, "Currents"])),
  ...Object.fromEntries(REC.map((c) => [c, "Recurrents"])),
  ...Object.fromEntries(GOLD.map((c) => [c, "Gold"])),
};

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const cat = (name) =>
  `(SELECT id FROM categories WHERE station_id=${q(STATION)} AND name=${q(name)})`;
const clk = (name) =>
  `(SELECT id FROM clocks WHERE station_id=${q(STATION)} AND name=${q(name)})`;

const out = [];
const w = (s = "") => out.push(s);

// ---------------------------------------------------------------------------- header
w(`-- M4 seed for The BOLT — GENERATED by tools/m4-seed.mjs. Do not hand-edit.`);
w(`-- Regenerate after any change to m4-format.mjs or clock-order.mjs.`);
w(`--`);
w(`-- ${Object.keys(SHAPES).length} clocks over ${FORMAT_CYCLE_WEEKS} rotation weeks`);
w(`-- (${168 * FORMAT_CYCLE_WEEKS} grid cells). Golden Hour alternates A/B variants by`);
w(`-- (week + dow) % 2, which is why the cycle is ${FORMAT_CYCLE_WEEKS} weeks rather than 1.`);
w(`--`);
w(`-- PREREQUISITE: run sync-library first. song_categories derives from`);
w(`-- songs.rdj_subcategory_id; the mirror is a derived cache, never a source of truth.`);
w(``);
w(`BEGIN;`);
w(``);

// ---------------------------------------------------------------------------- teardown
w(`-- Teardown. Logs are dropped because their log_items reference clock_positions;`);
w(`-- a seed that left them would orphan every approved log against clocks that no`);
w(`-- longer exist.`);
w(`DELETE FROM log_items WHERE log_id IN (SELECT id FROM logs WHERE station_id = ${q(STATION)});`);
w(`DELETE FROM logs WHERE station_id = ${q(STATION)};`);
w(`DELETE FROM format_grid WHERE station_id = ${q(STATION)};`);
w(`DELETE FROM clock_positions WHERE clock_id IN (SELECT id FROM clocks WHERE station_id = ${q(STATION)});`);
w(`DELETE FROM clocks WHERE station_id = ${q(STATION)};`);
w(`DELETE FROM rules WHERE station_id = ${q(STATION)};`);
w(`DELETE FROM song_categories WHERE category_id IN (SELECT id FROM categories WHERE station_id = ${q(STATION)});`);
w(`DELETE FROM categories WHERE station_id = ${q(STATION)};`);
w(``);

// ------------------------------------------------------------------- station rotation
w(`-- Rotation: the grid repeats over ${FORMAT_CYCLE_WEEKS} weeks. The epoch anchors week 0 and must`);
w(`-- never move — changing it flips which variant every Golden Hour cell resolves to.`);
w(`UPDATE stations SET format_cycle_weeks = ${FORMAT_CYCLE_WEEKS}, format_cycle_epoch = ${q(EPOCH)}::timestamp`);
w(`  WHERE id = ${q(STATION)};`);
w(``);

// ---------------------------------------------------------------------------- categories
w(`-- Parent music categories`);
w(`INSERT INTO categories (station_id, name, kind, default_target_turnover_hours) VALUES`);
w([...["Currents", "Recurrents", "Gold"].map((n) => `  (${q(STATION)}, ${q(n)}, 'music', NULL)`),
   `  (${q(STATION)}, 'Discovery', 'music', ${Math.round(TURNOVER.Discovery ?? 37)})`].join(",\n") + ";");
w(``);

w(`-- Child music categories. default_target_turnover_hours is the SOLVED turnover from`);
w(`-- tools/depth-solver.mjs, not an aspiration: depth was chosen to land these.`);
const children = [...CUR, ...REC, ...GOLD];
w(`INSERT INTO categories (station_id, name, kind, parent_id, default_target_turnover_hours) VALUES`);
w(children.map((c) =>
  `  (${q(STATION)}, ${q(c)}, 'music', ${cat(PARENT[c])}, ${Math.round(TURNOVER[c] ?? 0) || "NULL"})`
).join(",\n") + ";");
w(``);

w(`-- F is the late-stage fallback: it exists so that an hour-length miscalculation or a`);
w(`-- pool that cannot fill has something legal to take rather than leaving dead air. It`);
w(`-- is never called by a clock position and costs nothing to carry.`);
w(`INSERT INTO categories (station_id, name, kind, default_target_turnover_hours) VALUES`);
w(`  (${q(STATION)}, 'F', 'music', NULL),`);
w(`  (${q(STATION)}, 'GDEEP', 'music', NULL);`);
w(``);

// Every non-music key in the contract gets a category, not just the ones a clock
// currently calls. Heritage Backsells has no content and no position yet -- but the
// contract declares its subcategory, and a declared mapping with no category is exactly
// the M2-era failure where subcategory 34 sat unmapped and nobody noticed.
const musicCats = new Set([...CUR, ...REC, ...GOLD, "Discovery", "F", "GDEEP"]);
const imagingCats = [...new Set([
  ...Object.values(IMAGING).flatMap((o) => Object.keys(o)),
  ...Object.keys(SUBCAT).filter((k) => !musicCats.has(k)),
])].sort();
w(`-- Imaging categories. Per-block TOH IDs (subcats 40-48) so the hour opens with what`);
w(`-- the station IS at that moment rather than one generic ID everywhere.`);
w(`INSERT INTO categories (station_id, name, kind, default_target_turnover_hours) VALUES`);
w(imagingCats.map((c) =>
  `  (${q(STATION)}, ${q(c)}, 'imaging', ${c.startsWith("TOH ") ? TOH_TURNOVER : "NULL"})`
).join(",\n") + ";");
w(``);

// ------------------------------------------------------------------------ song mapping
w(`-- Library <-> clockset contract. Identity is the RadioDJ subcategory ID; the mirror`);
w(`-- follows RadioDJ (ADR-0001 §3.2 stage 1). B is subcat 1 alone since the 2026-08-02`);
w(`-- consolidation retired subcat 5.`);
w(`INSERT INTO song_categories (song_id, category_id)`);
w(`SELECT s.id, c.id FROM songs s JOIN categories c ON c.station_id = s.station_id`);
w(`WHERE s.station_id = ${q(STATION)} AND (`);
w(Object.entries(SUBCAT).map(([name, ids]) =>
  `  (c.name = ${q(name)} AND s.rdj_subcategory_id ${ids.length > 1 ? `IN (${ids.join(",")})` : `= ${ids[0]}`})`
).join(" OR\n"));
w(`)`);
w(`ON CONFLICT ON CONSTRAINT song_categories_song_category_unique DO NOTHING;`);
w(``);

// ---------------------------------------------------------------------------- clocks
const codes = Object.keys(SHAPES);
w(`-- One clock per block. GHa/GHb and DNa/DNb are variants of one identity (see`);
w(`-- IDENTITY in m4-format.mjs) and share a TOH pool, but are separate clocks because`);
w(`-- their position order differs.`);
w(`INSERT INTO clocks (station_id, name, length_minutes, notes) VALUES`);
w(codes.map((c) => `  (${q(STATION)}, ${q(c)}, 60, ${q(BLOCKS[c])})`).join(",\n") + ";");
w(``);

// -------------------------------------------------------------------- clock positions
w(`-- Clock positions. Music is placed by two-level proportional spread (tier first, then`);
w(`-- category within tier); imaging is woven in contextually — a New-Music sweeper ahead`);
w(`-- of a new track, a Gold Backsell behind a gold one. Emitted from clockSequence() so`);
w(`-- this matches tools/clock-order.mjs exactly.`);
w(`--`);
w(`-- constraints.fallbackCategoryId is the governing fallback policy: currents never`);
w(`-- fall back to gold. Unplanned fallback is still programming — under M3, G2010 carried`);
w(`-- 651 fallback slots on top of its own 368, and the station's gold-heavy sound was a`);
w(`-- symptom of shallow currents rather than a design choice.`);
const rows = [];
let totalPositions = 0;
for (const code of codes) {
  const seq = clockSequence(code);
  totalPositions += seq.length;
  seq.forEach((item, i) => {
    const fb = fallbackFor(item.cat, code);
    const constraints = fb
      ? `(SELECT jsonb_build_object('fallbackCategoryId', ${cat(fb)}::text))`
      : "NULL";
    const type = item.kind === "imaging" ? "sweeper" : "category";
    const offset = i === 0 ? "0" : "NULL";
    rows.push(`  (${clk(code)}, ${i + 1}, '${type}', ${cat(item.cat)}, ${offset}, ${constraints})`);
  });
}
w(`INSERT INTO clock_positions (clock_id, sort_order, position_type, category_id, target_offset_seconds, constraints) VALUES`);
w(rows.join(",\n") + ";");
w(``);

// ------------------------------------------------------------------------ format grid
w(`-- Format grid: ${168 * FORMAT_CYCLE_WEEKS} cells (${FORMAT_CYCLE_WEEKS} weeks x 168 hours), station-local.`);
w(`-- Golden Hour resolves to GHa or GHb by (week + dow) % 2, so a listener in a fixed`);
w(`-- weekly slot gets the other variant next week.`);
const grid = [];
for (let week = 0; week < FORMAT_CYCLE_WEEKS; week++)
  for (let dow = 0; dow < 7; dow++)
    for (let hour = 0; hour < 24; hour++)
      grid.push(`  (${q(STATION)}, ${dow}, ${hour}, ${week}, ${clk(cellFor(dow, hour, week))})`);
w(`INSERT INTO format_grid (station_id, day_of_week, hour, week_in_cycle, clock_id) VALUES`);
w(grid.join(",\n") + ";");
w(``);

// ------------------------------------------------------------------------------ rules
w(`-- Rules. Vertical separation (artist/title) keeps unlike things apart within an hour;`);
w(`-- horizontal separation keeps a song off the same TIME OF DAY on successive plays.`);
w(`--`);
w(`-- Horizontal is scoped to currents and R1 ONLY. Applied uniformly it made things`);
w(`-- worse — R1 lost 19pp and Discovery yielded on 93% of slots, and a yield drops album`);
w(`-- separation and tempo clash with it. Params are yield-capped at <=25%.`);
const ruleRows = [
  `  (${q(STATION)},'global',NULL,'artist_separation','{"minMinutes":45}','hard',NULL)`,
  `  (${q(STATION)},'global',NULL,'title_separation','{"minMinutes":150}','hard',NULL)`,
  `  (${q(STATION)},'category',${cat("Currents")},'artist_separation','{"minMinutes":30}','hard',NULL)`,
  `  (${q(STATION)},'global',NULL,'tempo_clash','{"maxJump":2}','soft',0.2)`,
  `  (${q(STATION)},'global',NULL,'era_spread','{}','soft',0.15)`,
  `  (${q(STATION)},'category',${cat("Recurrents")},'max_per_hour','{"count":6}','hard',NULL)`,
];
for (const [c, h] of Object.entries(HORIZONTAL)) {
  ruleRows.push(`  (${q(STATION)},'category',${cat(c)},'horizontal_separation',` +
    `'${JSON.stringify(h)}','hard',NULL)`);
}
w(`INSERT INTO rules (station_id, scope, scope_ref, rule_type, params, hardness, weight) VALUES`);
w(ruleRows.join(",\n") + ";");
w(``);

// ----------------------------------------------------------------------- self-assertion
w(`-- Assert the seed landed. A silent partial seed is far worse than a failed one: the`);
w(`-- station would generate logs against a half-built clockset and nobody would know`);
w(`-- until air. Each check aborts the transaction rather than warning.`);
w(`DO $$`);
w(`DECLARE n int;`);
w(`BEGIN`);
w(`  SELECT count(*) INTO n FROM clocks WHERE station_id = ${q(STATION)};`);
w(`  IF n <> ${codes.length} THEN RAISE EXCEPTION 'expected ${codes.length} clocks, got %', n; END IF;`);
w(`  SELECT count(*) INTO n FROM format_grid WHERE station_id = ${q(STATION)};`);
w(`  IF n <> ${168 * FORMAT_CYCLE_WEEKS} THEN RAISE EXCEPTION 'expected ${168 * FORMAT_CYCLE_WEEKS} grid cells, got %', n; END IF;`);
w(`  SELECT count(*) INTO n FROM clock_positions cp JOIN clocks c ON c.id = cp.clock_id`);
w(`    WHERE c.station_id = ${q(STATION)};`);
w(`  IF n <> ${totalPositions} THEN RAISE EXCEPTION 'expected ${totalPositions} clock positions, got %', n; END IF;`);
w(`  -- Every position must resolve a category. A NULL here is a category name in the`);
w(`  -- generator that does not exist in the categories table — the M2-era failure where`);
w(`  -- subcategory 34 sat unmapped and nobody noticed.`);
w(`  SELECT count(*) INTO n FROM clock_positions cp JOIN clocks c ON c.id = cp.clock_id`);
w(`    WHERE c.station_id = ${q(STATION)} AND cp.category_id IS NULL;`);
w(`  IF n > 0 THEN RAISE EXCEPTION '% clock positions have no category', n; END IF;`);
w(`  -- Every music category a clock calls must actually have songs mapped to it.`);
w(`  SELECT count(*) INTO n FROM categories cat WHERE cat.station_id = ${q(STATION)}`);
w(`    AND cat.kind = 'music' AND cat.parent_id IS NOT NULL`);
w(`    AND NOT EXISTS (SELECT 1 FROM song_categories sc WHERE sc.category_id = cat.id);`);
w(`  IF n > 0 THEN RAISE EXCEPTION '% music categories have no songs — re-sync the library first', n; END IF;`);
w(`END $$;`);
w(``);
w(`COMMIT;`);

process.stdout.write(out.join("\n") + "\n");
